### ISSUE TITLE
运行这个项目是不是要先安装nvm

### ISSUE THREAD

**Issue by foreversue** [Aaaaash/LanguageServices-WebIDE#3]
$ yarn prepare:env
yarn run v1.12.3
warning ..\package.json: No license field
$ ./node_modules/.bin/gulp download-java-server && ./node_modules/.bin/gulp inst
all-py-server
[15:52:31] Using gulpfile ~\LanguageServices-WebIDE\gulpfile.js
[15:52:31] Starting 'download-java-server'...
[15:52:34] Finished 'download-java-server' after 2.5 s
[gulp] Downloading http://download.eclipse.org/jdtls/snapshots/jdt-language-serv
er-latest.tar.gz... 0.06753343139753774% 0.5803846614481769% Done
[15:52:44] Using gulpfile ~\LanguageServices-WebIDE\gulpfile.js
[15:52:44] Starting 'install-py-server'...
[15:52:44] Finished 'install-py-server' after 7.87 ms
'sudo' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:651
    throw err;
    ^

Error: Command failed: sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/sim
ple 'python-language-server[all]'
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at cp.exec (C:\Users\su\LanguageServices-WebIDE\gulpfile.js:26:10)
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by Aaaaash** [comment]
需要安装 pip，另外这个脚本只能在 macOS 和 Linux 下运行，windows 的话改一下 gulpfile.js 里的 install-py-server ，去掉 sudo 就好了

**Comment by foreversue** [comment]
目标是想要让monaco编辑器能够识别json语法，如果直接参考利用LSP为Monaco编辑器提供语言服务以及Web连接LSP那块的话，是否还需要安装pip？

**Comment by Aaaaash** [comment]
那你不需要这个LSP，Monaco 自带 JSON的LSP

foreversue <notifications@github.com> 于 2018年12月4日周二 23:34写道：

**Comment by foreversue** [comment]
在TypeFox/monaco-languageclient库里的example / src /server.ts 为应用程序打开web socket ，并在当前进程中启动语言服务器或作为外部进程。这里指的就是打开LSP吗？

**Comment by Aaaaash** [comment]
指的是连接到你的LSP服务，外部进程需要靠LSP服务启动，也就是说 websocket
只是做了一层中转，这里的外部进程就是真正提供代码提示的程序，每个语言的实现都不同。

foreversue <notifications@github.com> 于 2018年12月4日周二 23:47写道：

**Comment by foreversue** [comment]
是否是让monaco编辑器理解各类语言（ C, python, js, java 等）并作出语法提示报错等功能（在monaco编辑器里写入某种语言，然后monaco编辑器连接到LSP，LSP识别后再反馈给monaco编辑器，编辑器作出语言识别，给出语言提示报错等功能）参考TypeFox/monaco-languageclient库里的example / src /server.ts 这可以了？

**Comment by Aaaaash** [comment]
是
foreversue <notifications@github.com> 于 2018年12月5日周三 00:17写道：
